###
//Get All Users
GET http://localhost:5000/users

###
//Get Users By Id
GET http://localhost:5000/users/9fb06ab0-7c85-408c-852f-48388ff9e467

###
//Create User
POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "Ari Lesmana",
  "email": "420@gmail.com",
  "telephone": "085695951121",
  "university": "London School",
  "nim": "19411012",
  "password": "123",
  "confPassword": "123",
  "role": "user"
}

###
//Update User
PUT   http://localhost:5000/users/9fb06ab0-7c85-408c-852f-48388ff9e467
Content-Type: application/json

{
  "name": "Ari Lesmana",
  "email": "420@gmail.com",
  "telephone": "085695951121",
  "university": "London School",
  "nim": "19411014",
  "password": "123",
  "confPassword": "123",
  "role": "user"
}

###
// delete user
DELETE http://localhost:5000/users/9fb06ab0-7c85-408c-852f-48388ff9e467

###
// Login admin
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "ajicooljazz38@gmail.com",
  "password": "123"
}

###
// Login user
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "jimmyandTheGank@gmail.com",
  "password": "123"
}

###
// Me
GET http://localhost:5000/session

###
// Logout
DELETE http://localhost:5000/logout