###
//Get All Users
GET http://localhost:5000/users

###
//Get Users By Id
GET http://localhost:5000/users/2e07c985-448d-4e6d-8d1b-0749388b1ba9

###
//Create User
POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "Jason Ranti",
  "email": "jjBoy@gmail.com",
  "telephone": "085695951121",
  "university": "Institut Teknologi Bandung",
  "nim": "22411011",
  "password": "123",
  "confPassword": "123",
  "role": "admin"
}

###
//Update User
PUT   http://localhost:5000/users/1b6d35d2-a2c0-4c7b-8c26-00cdc3fd5a48
Content-Type: application/json

{
  "name": "M Aji Perdana",
  "email": "ajicooljazz38@gmail.com",
  "telephone": "085695951121",
  "university": "Universitas Bandar Lampung",
  "nim": "19411011",
  "password": "123",
  "confPassword": "123",
  "role": "admin"
}

###
// delete user
DELETE http://localhost:5000/users/44f66609-20f6-4939-89e5-873370f67a0a

###
// Login admin
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "ajicooljazz38@gmail.com",
  "password": "123"
}

###
// Login user
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "jimmyandTheGank@gmail.com",
  "password": "123"
}

###
// Me
GET http://localhost:5000/session

###
// Logout
DELETE http://localhost:5000/logout